global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api-gateway'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'order-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['order-service:8080']

  - job_name: 'user-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['user-service:8080']

  - job_name: 'matching-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['matching-service:8080']

  - job_name: 'portfolio-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['portfolio-service:8080']
      
  - job_name: 'discovery-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['discovery-service:8761']