{
 "title": "Resilience4j",
 "description": "Resilience4j Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "application",
    "label": "Application",
    "query": {
     "query": "label_values(jvm_info,application)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state,instance)"
    }
   },
   {
    "name": "circuitbreaker_name",
    "label": "CircuitBreaker Name",
    "query": {
     "query": "label_values(resilience4j_circuitbreaker_state, name)"
    }
   },
   {
    "name": "retry_name",
    "label": "Retry Name",
    "query": {
     "query": "label_values(resilience4j_retry_calls_total,name)"
    }
   },
   {
    "name": "bulkhead_name",
    "label": "Bulkhead Name",
    "query": {
     "query": "label_values(resilience4j_bulkhead_available_concurrent_calls, name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of closed CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"closed\"})"
    }
   ]
  },
  {
   "title": "Number of open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=~\"open|forced_open\"})"
    }
   ]
  },
  {
   "title": "CircuitBreaker States",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_state{instance=~\"$instance\"}",
     "legendFormat": "{{ name }}: {{ state }}"
    }
   ]
  },
  {
   "title": "Number of half_open CircuitBreaker",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(resilience4j_circuitbreaker_state{state=\"half_open\"})"
    }
   ]
  },
  { "title": "CircuitBreaker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "circuitbreaker_name" },
  {
   "title": "Failure Rate: $circuitbreaker_name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_failure_rate{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Call rate: $circuitbreaker_name",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }} "
    },
    {
     "expr": "rate(resilience4j_circuitbreaker_calls_total{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind  }} "
    }
   ]
  },
  {
   "title": "Buffered calls: $circuitbreaker_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 8, "y": 21 },
   "targets": [
    {
     "expr": "resilience4j_circuitbreaker_buffered_calls{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "resilience4j_circuitbreaker_max_buffered_calls{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}",
     "legendFormat": "maximum"
    }
   ]
  },
  {
   "title": "Average call durations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 29 },
   "targets": [
    {
     "expr": "increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m]) / increase(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])",
     "legendFormat": "{{ kind }}"
    },
    {
     "expr": "sum(increase(resilience4j_circuitbreaker_calls_seconds_sum{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m])) / sum(increase(resilience4j_circuitbreaker_calls_seconds_count{instance=~\"$instance\",name=~\"$circuitbreaker_name\"}[1m]))",
     "legendFormat": "total "
    }
   ]
  },
  { "title": "Retry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 }, "repeat": "retry_name" },
  {
   "title": "Rate retryable calls: $retry_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "targets": [
    {
     "expr": "rate(resilience4j_retry_calls_total{application=~\"$application\",name=~\"$retry_name\",}[1m])",
     "legendFormat": "{{ kind }}"
    }
   ]
  },
  { "title": "Bulkhead", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 }, "repeat": "bulkhead_name" },
  {
   "title": "Bulkhead: $bulkhead_name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "resilience4j_bulkhead_available_concurrent_calls{application=~\"$application\", name=~\"$bulkhead_name\"}",
     "legendFormat": "Available Calls"
    },
    {
     "expr": "resilience4j_bulkhead_max_allowed_concurrent_calls{application=~\"$application\",name=~\"$bulkhead_name\"}",
     "legendFormat": "maximum"
    }
   ]
  }
 ]
}